### ISSUE TITLE
Failure when I try to install version 1.0.0

### ISSUE THREAD

**Issue by waveiro** [asdf-community/asdf-deno#13]
When I try to run this command:

`asdf install deno 1.0.0`

I get the following error message: 

```
 gzip: /home/waveiro/.asdf/installs/deno/1.0.0/bin/deno.gz: not in gzip format
 Fail: Could not uncompress
 Fail: An error occurred
```
 
I'm using this version of asdf:

```
asdf --version
v0.7.8-4a3e3d6
```

**Comment by waveiro** [comment]
The solution is to run one of this:

`asdf plugin update deno`

or 

`asdf plugin update --all`


And then install Deno's latest version:

`asdf install deno 1.0.0`

**Comment by imbsky** [comment]
Yeah! It's useful for users who have the same problem! Thanks for leaving a note.

**Comment by brandonpsmith** [comment]
@waveiro thanks. This saved me some time when I had the same error.

**Comment by imbsky** [comment]
I pinned this issue because it will probably help a lot of people.
