### ISSUE TITLE
Shims support?

### ISSUE THREAD

**Issue by xeho91** [asdf-community/asdf-deno#14]
Is this plugin supporting shims?

I am using deno v1.0.2, and I have installed [velociraptor](https://github.com/umbopepato/velociraptor/tree/master) which is an alternative for npm scripts.
It provides a command `vr`, which can be used globally.

However, the command itself doesn't work, until I add the following line of code  to my `.zshrc` file.
```sh
export PATH="/home/<user>/.deno/bin:$PATH"
```

Normally, when installing for example node or any package installed globally with npm/yarn, the shims would be located in this location:
```sh
$ which nodemon
/home/<user>/.asdf/shims/nodemon
```

I tried to troubleshoot this issue, and on the official documentation, I found this section:
https://asdf-vm.com/#/core-manage-asdf-vm?id=having-issues

I ensured that the sourcing file is at the bottom of my profile, but that wasn't the case.

Is it likely to be a problem with my configuration or this plugin doesn't add shims?

**Additional info:**
I am using WSL2 with Ubuntu (20.04 LTS) on my Windows10

**Comment by imbsky** [comment]
Yes, I think it makes sense. It's easy to implement. Do you try that?

**Comment by imbsky** [comment]
I didn't have much time this month and don't think I can give you a pointer, so I opened the PR myself.

**Comment by imbsky** [comment]
This should be available on the latest master. If you want to use this with an already-installed version, you need to manually create a deno install root. But the new installation process will take care of this automatically.

**Comment by imbsky** [comment]
Like this:

```bash
mkdir -p .asdf/installs/deno/<VERSION>/.deno/bin
```
