### ISSUE TITLE
`deno install` doesn't behave according to the manual

### ISSUE THREAD

**Issue by jsejcksn** [asdf-community/asdf-deno#17]
On the [script installer](https://deno.land/manual/tools/script_installer) manual page it says:

> The installation root is determined, in order of precedence:
>
> - `--root` option
> - `DENO_INSTALL_ROOT` environment variable
> - `$HOME/.deno`

However, when installing scripts using an asdf-installed version of deno, they are installed to `$ASDF_DIR/installs/deno/<CURRENT_VERSION>/.deno/bin`.

I am using macOS and the `DENO_INSTALL_ROOT` variable is not set in my environment.

Example output:

```shell
> deno install --name denoscript main.ts
Download https://deno.land/x/semver@v1.0.0/mod.ts
Download https://deno.land/std@0.57.0/flags/mod.ts
Download https://deno.land/std@0.57.0/_util/assert.ts
Compile file:///path/redacted/for/privacy/main.ts
✅ Successfully installed denoscript
/path/redacted/for/privacy/.asdf/installs/deno/1.1.0/.deno/bin/denoscript
```

**Comment by imbsky** [comment]
It's deliberately set here. For example, without this, the user had to manually set the path for DENO_INSTALL_ROOT.

https://github.com/asdf-community/asdf-deno/blob/9d55faa3eb833a4917c7277d3e1e82b9f0295b54/bin/exec-env#L4-L6

So, the plugin overwrites DENO_INSTALL_ROOT unless it's defined by the user and exposes it as an executable file.

https://github.com/asdf-community/asdf-deno/blob/9d55faa3eb833a4917c7277d3e1e82b9f0295b54/bin/list-bin-paths#L3

**Comment by imbsky** [comment]
Related issue: https://github.com/asdf-community/asdf-deno/issues/14

**Comment by imbsky** [comment]
I want to hear from the community to make the development experience better, and I want to hear your opinion about this behavior. Don't hesitate to write all your opinions! We are very positive about hearing that :)

**Comment by jsejcksn** [comment]
> without this, the user had to manually set the path for DENO_INSTALL_ROOT

If the user doesn't set this variable, then, according to the manual, scripts should be installed to `$HOME/.deno/bin`.

> Don't hesitate to write all your opinions! We are very positive about hearing that :)

Alright—sure. 😀

With the current behavior, if a user has not set `DENO_DIR` or `DENO_INSTALL_ROOT`, when the user installs a newer version of deno and deletes the old one:

  - the installed scripts will be deleted
  - any cached modules will be deleted

This is not good. Cached modules and installed scripts do not depend on specific versions of deno, so they should remain in place no matter which version of deno is being used.

I'm not sure when it changed, but in a previous version of this plugin, deno would still cache modules and install to the directories specified by following the rules of the manual.

**I think it is a good idea to follow the behavior specified in the manual.**

**Comment by imbsky** [comment]
Thanks for your detailed comment!

> This is not good. Cached modules and installed scripts do not depend on specific versions of deno, so they should remain in place no matter which version of deno is being used.

I think the installed script may depend on the Deno version. But the cache will certainly not depend on it if Deno is properly designed.

**Comment by imbsky** [comment]
By the way, at first I thought that it was clean to remove all relevant files when you uninstall. But I don't really have a strong opinion on this. Because half of it is just taste or intuition.

**Comment by jsejcksn** [comment]
The "installed scripts" are not actually JS/TS scripts, but are just shell script "shortcuts" which run the original JS/TS files... so, they won't depend on a specific version of deno. 😄

Example:

```shell
> cat /path/redacted/for/privacy/.deno/bin/asdf-update-deno
#!/bin/sh
# generated by deno install
deno "run" "--allow-run" "file:///path/redacted/for/privacy/.deno/bin/asdf-update-deno.bundle.js" "$@"
```

**Comment by jsejcksn** [comment]
@smorimoto Have you had any time to think about addressing this? It's causing issues for others using tools which rely on files being in the locations specified by the manual: https://github.com/justjavac/typescript-deno-plugin/issues/65

**Comment by smorimoto** [comment]
Oh, I'm sorry. I forgot this because I had taken some exams. I will be in an area with unstable internet access until the 29th, so it will be difficult to work until the 29th. Well, I'm very positive about addressing with this.

**Comment by jsejcksn** [comment]
From https://github.com/justjavac/typescript-deno-plugin/issues/65#issuecomment-666245412:

> The main reason I implemented this is because I thought it would be nice to be able to cleanup everything completely when uninstalling.

@smorimoto In my opinion, this is an anti-pattern because it opposes the intention of the cache and installation of scripts.

Deno is different from some other software in regard to versioning. It does not support the concept of specifying that a particular version of a script is compatible with a particular version of Deno. (This implementation is left to the programmer, using [`Deno.version`](https://doc.deno.land/https/github.com/denoland/deno/releases/latest/download/lib.deno.d.ts#Deno.version) in the script.) (See [manual:Stability](https://deno.land/manual/runtime/stability))

## Script installation

Script installations aren't actually "installations" in the traditional sense of compiling/copying files. From [manual:Script installer](https://deno.land/manual/tools/script_installer):

> This command creates a thin, executable shell script which invokes `deno` using the specified CLI flags and main module. It is placed in the installation root's `bin` directory.

Here is an example of the contents of an installed script:

```sh
#!/bin/sh
# generated by deno install
deno "run" "--allow-run" "file:///path/to/my-script.bundle.js" "$@"
```

In the example above, the "installed script" simply calls `deno` from the `PATH` and runs the script located at `file:///path/to/my-script.bundle.js`. (This could also be a remote resource on a networked drive or the internet.)

These installed scripts don't inherently depend on a particular version of Deno. Any version dependency is specified in the script code itself, so removing them on uninstall of a particular version makes them unavailable to all other versions of Deno, but still leaves the script wherever it's located. It just makes it unavailable for use as a binary.

## Caching

From [manual:Introduction](https://deno.land/manual#other-key-behaviors):

> **Other key behaviors**
> - Remote code is fetched and cached on first execution, and never updated until the code is run with the `--reload` flag. (So, this will still work on an airplane.)
> - Modules/files loaded from remote URLs are intended to be immutable and cacheable.

Since the cache is designed to be immutable, it is undesirable for it to be removed/cleared when uninstalling a specific version of Deno.

---

Hopefully I've detailed the reasons that cached files and installed scripts should not be placed in locations that will be removed (deleted or removed from `PATH`) when a specific version of Deno is uninstalled. If any of my message is unclear, please let me know so I can fix it. Thanks!

**Comment by smorimoto** [comment]
That makes sense, but I also care that many users want it out-of-the-box. What do you think about stop overriding `DENO DIR`by default and continuing to overriding `DENO_INSTALL_ROOT` by default?

**Comment by smorimoto** [comment]
Of course, this has some tradeoffs, as you say.

**Comment by jsejcksn** [comment]
> many users want it out-of-the-box

In this statement:

  - Who are the "many users"?
  - What is "it"?

> What do you think about stop overriding `DENO DIR`by default and continuing to overriding `DENO_INSTALL_ROOT` by default?

I think overriding any environment variables which are not exclusive to `asdf` will be a surprise to users. What do you think is an advantage of deleting cache or installed script wrappers? Why would either of these be overridden?

**Comment by smorimoto** [comment]
I heard from the Japanese community that many users have the same opinion as this issue. And the only way to do this right now is to overwrite `DENO_INSTALL_ROOT`. https://github.com/asdf-community/asdf-deno/issues/14

**Comment by smorimoto** [comment]
https://asdf-vm.com/#/plugins-create?id=binlist-bin-paths

**Comment by jsejcksn** [comment]
Thank you for that information. Now I see the the other users' difficulty. **This seems to be a `PATH`-related issue. Do you agree?**

Also, I'm still hoping you will respond to the other question I asked:

> I think overriding any environment variables which are not exclusive to `asdf` will be a surprise to users. What do you think is an advantage of deleting cache or installed script wrappers?

---

In regard to shims: I think this is a unique scenario because the script wrappers installed by Deno are already "shims" and they're not version-specific binaries that other softwares use.

I will think more about this. An initial thought is not to override `DENO_INSTALL_ROOT`, but instead create symlinks to the script wrappers, and place those symlinks in `~/.asdf/installs/deno/<VERSION>/.deno/bin`. That way, installed scripts aren't deleted when deleting a version of Deno, and the users who rely on the asdf shims for their `PATH` will get the same benefits until they uninstall that version of Deno. (Which is what they expect, yes?)

**Comment by Nitive** [comment]
Hello! I recently run into simular issue. [Official vscode extension](https://github.com/denoland/vscode_deno) expects deno cache to be located at `~/Library/Caches/deno` (on macOS) but with asdf-installed deno its path is `~/.asdf/installs/deno/1.4.0/.cache/deno`. So all imports marked red and autocomplete does not work.

As a workaround I explitly set DENO_DIR in my rc file
```
source /usr/local/opt/asdf/asdf.fish
export DENO_DIR="$HOME/Library/Caches/deno"
```

**Comment by smorimoto** [comment]
Oh, I'm sorry. I was busy and forgot about this. I've thought about this for a while, but this implementation of asdf-deno seems to cause too much confusion for the vscode-deno users. So, I currently have no objection to removing this asdf-deno specific behavior. Go ahead and open a PR!

**Comment by smorimoto** [comment]
@Nitive Yeah, sure. Your workaround (solution) is correct. This is because the vscode-deno implementation looks like this.
https://github.com/denoland/vscode_deno/blob/master/core/deno.ts#L4-L34

**Comment by smorimoto** [comment]
By the way, of course I can work on this. Please let me know if you have no bandwidth.

**Comment by Nitive** [comment]
I've created a PR https://github.com/asdf-community/asdf-deno/pull/18 with removing custom cache folder.

I've kept custom `DENO_INSTALL_ROOT`, because removing it will be a breaking change, we need to think how to make this update.

Right now asdf creates files `$HOME/.asdf/shims/<executable-name>` for each executable and adds `$HOME/.asdf/shims` to PATH. To make update non-breaking we need to either

1. Tell asdf to create `$HOME/.asdf/shims/<executable-name>` for every file in `$HOME/.deno/bin`. Seems like we can't do it with `list-bin-paths`, because it accepts only relative paths
2. Or we can add `$HOME/.deno/bin` to PATH. Not sure if asdf have API for that

@smorimoto do you know if any of the listed above is possible?

**Comment by jsejcksn** [comment]
> I've kept custom `DENO_INSTALL_ROOT`, because removing it will be a breaking change, we need to think how to make this update.

@Nitive A breaking change is ok if the major version number is increased (according to [semver](https://semver.org/)). It should be documented, of course.

**Comment by smorimoto** [comment]
I think that `DENO_INSTALL_ROOT` can also be removed. There isn't much of a problem with users adding paths in the first place.

**Comment by smorimoto** [comment]
However, you need to know why this change was introduced. https://github.com/asdf-community/asdf-deno/issues/14

**Comment by jsejcksn** [comment]
> I think that `DENO_INSTALL_ROOT` can also be removed. There isn't much of a problem with users adding paths in the first place.

@smorimoto Since that is the only part left in the file, are you saying that the entire [`exec-env`](https://github.com/asdf-community/asdf-deno/blob/master/bin/exec-env) file can be deleted in the #18 PR?

> 1. Seems like we can't do it with `list-bin-paths`, because it accepts only relative paths

@Nitive Why not relative paths? You can use `..` to reference parent directories.

**Comment by Nitive** [comment]
> A breaking change is ok if the major version number is increased (according to semver). It should be documented, of course

Currently I can't see any version in this plugin. If we decide to make a breaking change, how it should be done?

> Why not relative paths? You can use .. to reference parent directories.

Fair enough. I'll try to do it

**Comment by smorimoto** [comment]
> Currently I can't see any version in this plugin. If we decide to make a breaking change, how it should be done?

Yes, but plugins aren't automatically updated. And there's nothing we call the "best way" to do that. We just make breaking changes.

**Comment by smorimoto** [comment]
> Why not relative paths? You can use .. to reference parent directories.

Yes. https://asdf-vm.com/#/plugins-create?id=binlist-bin-paths

**Comment by smorimoto** [comment]
> @smorimoto Since that is the only part left in the file, are you saying that the entire exec-env file can be deleted in the #18 PR?

If `DENO_INSTALL_ROOT` destroys something, I think we have no choice.

**Comment by smorimoto** [comment]
This issue should have been solved with the latest master. I will close it once, but please let me know if there are any problems.

**Comment by jsejcksn** [comment]
@smorimoto It looks like the environment variable `DENO_INSTALL_ROOT` is still being set in [`bin/exec-env`](https://github.com/asdf-community/asdf-deno/blob/master/bin/exec-env#L4-L6) ([permalink](https://github.com/asdf-community/asdf-deno/blob/feb058a5c9b1736fc54a598c1890c0752ab2aed1/bin/exec-env#L4-L6)), since it wasn't removed in #18, and no action was taken on these comments above:

  - https://github.com/asdf-community/asdf-deno/issues/17#issuecomment-699852710
  - https://github.com/asdf-community/asdf-deno/issues/17#issuecomment-699853347

Should I open a new issue?

**Comment by fschoenfeldt** [comment]
So now how do I install and more importantly, use global packages with this shim? 

What I now did is

```
ln -s ~/.asdf/installs/deno/1.18.0/.deno/bin/ ~/.deno/bin
```

If anyone else comes along this, this might be a workaround for you. (Keep in mind to use your actual deno version).
