### ISSUE TITLE
"Something went wrong" installing Deno 1.16.4

### ISSUE THREAD

**Issue by lucioeiras** [asdf-community/asdf-deno#25]
I'm using Ubuntu with WSL on Windows and when I try to install the latest version of Deno I got this error:

![image](https://user-images.githubusercontent.com/67290471/145659333-13ee0b2d-6d88-4771-8fb2-f6b25c82432e.png)

**Comment by smorimoto** [comment]
You need to install the unzip command - as the error clearly indicates.
