### ISSUE TITLE
Cannot install Deno v0.39.0

### ISSUE THREAD

**Issue by uki00a** [asdf-community/asdf-deno#7]
Hello there. Thanks for making this plugin!

I noticed that this plugin fails to install Deno v0.39.0.

```
$ asdf install deno 0.39.0
∗ Downloading and installing deno...

gzip: /home/uki00a/.asdf/installs/deno/0.39.0/bin/deno.gz: not in gzip format
Fail: Could not uncompress
Fail: An error occurred
```

I think this is probably due to the change of denoland/deno#4545.

Thanks.

**Comment by jsejcksn** [comment]
Seeing the same problem with 0.40.0. Haven't tried 0.39.x:

```
~ % asdf install deno 0.40.0
∗ Downloading and installing deno...
gunzip: ~/.asdf/installs/deno/0.40.0/bin/deno.gz: not in gzip format
\e[31mFail:\e[m Could not uncompress
\e[31mFail:\e[m An error occurred
```

**Comment by imbsky** [comment]
Update this plugin with
```
asdf plugin-update deno
```
and then try it again. This has been fixed in the latest master.

**Comment by jsejcksn** [comment]
@imbsky Thank you—that fixed the issue. Does `asdf` include any kind of plugin update notification system (for example, in response to certain commands), or do you know if it's been proposed?

**Comment by imbsky** [comment]
You're welcome. No, it doesn't. Also, I don't think there is a way to implement such a thing neatly due to the mechanism of the current plugin system.

**Comment by imbsky** [comment]
By the way, you can also use the `asdf plugin-update --all` command to update all plugins.

**Comment by jsejcksn** [comment]
@imbsky 👍 That's what I used.

In case you're interested: I think the suggested command syntax is [subcommands (space separated instead of using dashes)](https://github.com/asdf-vm/asdf/issues/645#issuecomment-580454351), so

```sh
asdf plugin update --all
```

vs

```sh
asdf plugin-update --all
```

Both are supported, but the design goal is the former.
